openapi: '3.0.3'
info:
  title: order
  description: order
  version: '1.0.0'
servers:
  - url: 'http://localhost:8086'
paths:
  /api/order/{orderId}:
    get:
      tags:
        - Order
      operationId: getOrderById
      description: 'get order by id'
      parameters:
        - in: path
          name: orderId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: './model/order.yaml'
  /api/order/order-item/{orderItemId}:
    get:
      tags:
        - Order
      operationId: getOrderItemById
      description: 'get order item by id'
      parameters:
        - in: path
          name: orderItemId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: './model/order-item.yaml'
  /api/order/good/{goodId}:
    get:
      tags:
        - Order
      operationId: getGoodById
      description: 'get good by id'
      parameters:
        - in: path
          name: goodId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: './model/good.yaml'
  /api/order/customer/{userId}:
    get:
      tags:
        - Order
      operationId: getOrdersByCustomer
      description: 'get orders ordered by a customer'
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './model/order.yaml'
  /api/order/driver/{userId}:
    get:
      tags:
        - Order
      operationId: getOrdersByDriver
      description: 'get orders delivered by a driver'
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './model/order.yaml'
  /api/order/handler/{userId}:
    get:
      tags:
        - Order
      operationId: getOrdersByHandler
      description: 'get orders handled by a handler'
      parameters:
        - in: path
          name: userId
          schema:
            type: integer
          required: true
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './model/order.yaml'
  /api/order/handler:
    put:
      tags:
        - Order
      operationId: updateDeliveryTime
      description: 'updates the expected delivery time of the order'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './req/modify-delivery-date-req.yaml'
      responses:
        '200':
          description: 'Success'
  /api/order/driver:
    put:
      tags:
        - Order
      operationId: updateDeliveryState
      description: 'updates the delivery state of the order'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './req/modify-delivery-state-req.yaml'
      responses:
        '200':
          description: 'Success'
