openapi: '3.0.3'
info:
  title: user
  description: user
  version: '1.0.0'
servers:
  - url: 'http://localhost:8082'
paths:
  /api/login:
    post:
      tags:
        - User
      operationId: login
      description: 'Login the user'
      requestBody:
        content:
          application/json:
            schema:
              $ref: './req/login-req.yaml'
      responses:
        '200':
          description: 'Success'
          content:
            application/json:
              schema:
                $ref: './resp/login-resp.yaml'
        '401':
          description: 'Unauthorized'
          content:
            application/json:
              schema:
                $ref: './error/unauthorized.yaml'