server:
  port: 8083
  error:
    include-message: always
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://discovery:8085/eureka/}
spring:
  application:
    name: map
#spring:
#  datasource:
#    url: jdbc:postgresql://localhost:5432/delivery-webapp-map?createDatabaseIfNotExist=true
#    username: postgres
#    password: admin
#    driver-class-name: org.postgresql.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
#    properties:
#      hibernate:
#        format_sql: true
#    generate-ddl: true
#  sql:
#    int:
#      mode: always
feign:
  chat:
    url: ${CHAT_FEIGN_URL:http://chat:8087/api}
  user:
    url: ${USER_FEIGN_URL:http://user:8082/api}
  order:
    url: ${ORDER_FEIGN_URL:http://order:8086/api}