server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8085/eureka/}
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5
    fetch-registry: true
    register-with-eureka: true
spring:
  cloud:
    gateway:
      routes:
      - id: map
        uri: lb://map
        predicates:
          - Path=/api/map/**
        filters:
          - RewritePath=/api/map(?<segment>/?.*), /api$\{segment}
      - id: chat
        uri: lb://chat
        predicates:
          - Path=/api/chat/**
        filters:
          - RewritePath=/api/chat(?<segment>/?.*), /api$\{segment}
      - id: order
        uri: lb://order
        predicates:
          - Path=/api/order/**
      - id: user
        uri: lb://user
        predicates:
          - Path=/api/user/**
        filters:
          - RewritePath=/api/user(?<segment>/?.*), /api$\{segment}
deliveryWebapp:
  jwtSecret: HwTaEBBb6AFEyteEasdBnXjaerVWdeTRnNOkLM4N
  jwtExpirationMs: 8640000