/**
 * user
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RoleEnum = 'CUSTOMER' | 'DRIVER' | 'HANDLER';

export const RoleEnum = {
    Customer: 'CUSTOMER' as RoleEnum,
    Driver: 'DRIVER' as RoleEnum,
    Handler: 'HANDLER' as RoleEnum
};

