/**
 * order
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DeliveryState = 'ACCEPTED' | 'PROCESSED' | 'EN_ROUTE' | 'COMPLETED';

export const DeliveryState = {
    Accepted: 'ACCEPTED' as DeliveryState,
    Processed: 'PROCESSED' as DeliveryState,
    EnRoute: 'EN_ROUTE' as DeliveryState,
    Completed: 'COMPLETED' as DeliveryState
};

