/**
 * order
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeliveryState } from './deliveryState';


export interface ModifyDeliveryStateReq { 
    orderId?: number;
    deliveryState?: DeliveryState;
}
export namespace ModifyDeliveryStateReq {
}


