/**
 * order
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Good } from './good';


export interface OrderItem { 
    id?: number;
    quantity?: number;
    price?: number;
    good?: Good;
}

