/**
 * order
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeliveryState } from './deliveryState';
import { OrderItem } from './orderItem';


export interface Order { 
    id?: number;
    userId?: number;
    handlerId?: number;
    driverId?: number;
    orderPlacementDate?: string;
    expectedDeliveryTime?: string;
    price?: number;
    items?: Array<OrderItem>;
    deliveryState?: DeliveryState;
}
export namespace Order {
}


